### ISSUE TITLE
Asking about computational speed !

### ISSUE THREAD

**Issue by VishantVadher** [shazraz/Vehicle-Lane-Detection-YOLOv2#1]
I am curious to know that it would work for my system near real time .?

System :
CPU : i7 - 4510U
RAM : 8 GB

Second system : 
CPU : i5 - 7th Gen
Ram : 8 GB
Graphics : Nvidia Ge-Force 920M

**Comment by shazraz** [comment]
I don't think it will. You'll probably need a better GPU to run this in real-time but it's worth trying out.
